// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL?.trim() || '';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY?.trim() || '';

// Validação de variáveis de ambiente (apenas em desenvolvimento)
if (import.meta.env.DEV) {
  if (!SUPABASE_URL) {
    console.error('❌ Missing env.VITE_SUPABASE_URL');
    console.error('Por favor, crie um arquivo .env na raiz do projeto com:');
    console.error('VITE_SUPABASE_URL=https://seu-projeto.supabase.co');
  }

  if (!SUPABASE_PUBLISHABLE_KEY) {
    console.error('❌ Missing env.VITE_SUPABASE_PUBLISHABLE_KEY');
    console.error('Por favor, adicione no arquivo .env:');
    console.error('VITE_SUPABASE_PUBLISHABLE_KEY=sua-chave-aqui');
  }
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL || 'https://placeholder.supabase.co',
  SUPABASE_PUBLISHABLE_KEY || 'placeholder-key',
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);